### ISSUE TITLE
increase prediction threshold

### ISSUE THREAD

**Issue by Albert57060839** [GuillaumeMougeot/biom3d#2]
Hi, can I know how to increase the prediction threshold? I modified the predict part and got no change in the result, I want to increase the confidence threshold to get a thinner airway model. Thank you!

**Comment by GuillaumeMougeot** [comment]
Hi @Albert57060839,
Thank you for your question. By default (if you let the option USE_SOFTMAX=True) the last layer of the model is a softmax layer, which means that if you have one type of object in your image, the model will output two predictions for each input image: one with the foreground and one with the background. In other words, for each voxel of your input image, the model will predict two values between 0 and 1 (one for the foreground and one for the background) and biom3d will select the maximum between these two values during postprocessing. This done in biom3d.predictors line 422:
```
if use_softmax:
        out = (logit.softmax(dim=0).argmax(dim=0)).int().numpy()  
```
where `logit` is your 'raw' prediction map with dimension (number_classes +1, height, width, depth)
One option is thus to output this `logit` instead of outputting the thresholding version, and then apply "manually" (i.e. write a small Python script) the thresholding method of your choice. Good news, logit outputting option is already included in biom3d, you simply have to add `return_logit: true` in the POSTPROCESSOR part of the config.yaml file of your trained model. Here is an example:
```
POSTPROCESSOR:
  fct: Seg
  kwargs:
    use_softmax: true
    keep_biggest_only: false
    keep_big_only: false
    return_logit: true #here is the line to add
```

Another option is to edit manually this line of code `out = (logit.softmax(dim=0).argmax(dim=0)).int().numpy()` with the postporcessing you prefer.  Please note, that you must have install biom3d using the source code for this change to be effective (cf. doc to do this type of installation).

A final option is to train your model with "USE_SOFTMAX=False" (careful you must set this before training in the config.py file), then the postprocessing that will be applied is a thresholding, that you find in biom3d.predictor line 431:
```
    else:
        out = (logit.sigmoid()>0.5).int().numpy()
```
here you can change the 0.5 to whatever threshold you like. Please note, that you must have install biom3d using the source code for this change to be effective. As this option is less used by users, it has been less tested, so don't hesitate to let me know if you spot a bug.
Guillaume

**Comment by Albert57060839** [comment]
Hi, thank you for your reply! I want to train the model with "USE_SOFTMAX=False", but after I made this change to the config.py file, I got this bug:

Training will start with a learning rate of 0.01
Current learning rate: 0.01
Epoch [  1/1000]
[time] start epoch
SLOW! 0 [time] data loading: 1.6706733703613281
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [20,0,0], thread: [822,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [20,0,0], thread: [823,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [20,0,0], thread: [696,0,0] Assertion `t >= 0 && t < n_classes` failed.
...
...
...
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [20,0,0], thread: [393,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [20,0,0], thread: [394,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [20,0,0], thread: [395,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xtx/Desktop/airway_segmentation/biom3d/biom3d/src/biom3d/train.py", line 261, in <module>
    train(config=args.config, path=args.log)
  File "/home/xtx/Desktop/airway_segmentation/biom3d/biom3d/src/biom3d/train.py", line 20, in train
    builder.run_training()
  File "/home/xtx/Desktop/airway_segmentation/biom3d/biom3d/src/biom3d/builder.py", line 586, in run_training
    read_config(
  File "/home/xtx/Desktop/airway_segmentation/biom3d/biom3d/src/biom3d/builder.py", line 51, in read_config
    return register_fct(**register_kwargs) 
  File "/home/xtx/Desktop/airway_segmentation/biom3d/biom3d/src/biom3d/trainers.py", line 54, in seg_train
    loss = loss_fn(pred, y)
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xtx/Desktop/airway_segmentation/biom3d/biom3d/src/biom3d/metrics.py", line 475, in forward
    ce_loss = self.ce(net_output, target[:, 0].long()) if self.weight_ce != 0 else 0
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xtx/Desktop/airway_segmentation/biom3d/biom3d/src/biom3d/metrics.py", line 399, in forward
    return super().forward(input, target.long())
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/xtx/anaconda3/envs/b3d/lib/python3.9/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Albert57060839** [comment]
Hi, I have achieved a thinner model by modifying this part:
out = (logit.softmax(dim=0).argmax(dim=0)).int().numpy()  
to
probabilities = logit.softmax(dim=0)
# Select the probabilities of class 1
probabilities_class_1 = probabilities[1]
# Apply the threshold to the probabilities of class 1
out = (probabilities_class_1 > 0.7).int().numpy() 
Thank you!

**Comment by GuillaumeMougeot** [comment]
Hi @Albert57060839,
Many thanks for your feedback and happy to see that you found a solution to your issues. About the error in your first message when you activated "USE_SOFTMAX=False", I forgot to mentioned that the default loss in biom3d (identical to nn-UNet loss) is not compatible with this option and thus must be switch to this:
```
TRAIN_LOSS = Dict(
    fct="DiceBCE",
    kwargs = Dict(name="train_loss", use_softmax=USE_SOFTMAX)
)

VAL_LOSS = Dict(
    fct="DiceBCE",
    kwargs = Dict(name="val_loss", use_softmax=USE_SOFTMAX)
)
```
I will close this issue, as you seem to have solved it.
Don't hesitate to open a new one, if you need it.
Guillaume
